### ISSUE TITLE
Print ADB errors

### ISSUE THREAD

**Issue by tuarrep** [SecTheTech/AMDH#15]
When adb encounters an error, typically when the devices isn't authorised, the program fails with a Trackback.

It should be clearer if it prints the adb error message and stop gracefully.

The trackback in my case was : 

``` bash
➜ python amdh.py -sA -a /home/nicolas/Android/Sdk/platform-tools/adb
[-] INFO: List of devices:
[-] INFO: The device 97UAY124RZ will be used.

Traceback (most recent call last):
  File "amdh.py", line 408, in <module>
    amdh()
  File "amdh.py", line 209, in amdh
    packages = adb_instance.list_installed_packages(arguments.app_type)
  File "/home/nicolas/Dev/playground/python/AMDH/core/adb.py", line 48, in list_installed_packages
    output_command = self.adb_exec(adb_command)
  File "/home/nicolas/Dev/playground/python/AMDH/core/adb.py", line 25, in adb_exec
    result = run(commands_array,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/nicolas/Android/Sdk/platform-tools/adb', '-s', '97UAY124RZ', 'shell', 'pm', 'list', 'packages', '-3']' returned non-zero exit status 1.

```

And the adb message was:

``` bash
➜ adb shell pm list packages -3
adb: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.

```

**Comment by A-YATTA** [comment]
Thanks for reporting the issue. I fixed it in the commit [https://github.com/SecTheTech/AMDH/commit/df02fd5b1009a10e8e32b3dc6c433a3948c0c4ca](df02fd5).
